version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      react_router:
        patterns:
          - react-router
          - "@react-router/*"
      vitest:
        patterns:
          - vitest
          - "@vitest/*"
